{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $url = concat('/xrowgis/gpxdownload/', $attribute.contentobject_id)}
<div class="des_text">
    <span class="i_gpx_text"><a href={$url|ezurl(,'full')}>Download</a></span>
</div>